<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BusinessesOldDbTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('businesses_old_db')->delete();

        \DB::table('businesses_old_db')->insert(
            array(
                0 =>
                array(
                    'id' => 1,
                    'full_name' => 'full_name',
                    'email' => 'email',
                    'phone' => 'phone',
                    'Password_partner' => 'Password_partner',
                    'plain_password' => 'plain_password',
                    'address' => 'address',
                    'created_dt' => 'created_dt',
                ),
                1 =>
                array(
                    'id' => 30,
                    'full_name' => 'PIR ABID SHAH',
                    'email' => 'pocketappsdelivetudio@gmail.com',
                    'phone' => '971527274271',
                    'Password_partner' => '',
                    'plain_password' => '',
                    'address' => 'RED RESIDENCE, 1401, SPORTS CITY, Other',
                    'created_dt' => '10/29/2018 22:43',
                ),
                2 =>
                array(
                    'id' => 43,
                    'full_name' => 'SUPERMEALS',
                    'email' => 'kickass@supermealsuae.com',
                    'phone' => '971555225667',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Motor City  New Bridge hill 2  Apartment 202  Dubai(OTHER)',
                    'created_dt' => '10/30/2018 19:03',
                ),
                3 =>
                array(
                    'id' => 44,
                    'full_name' => 'PURA',
                    'email' => 'mona@pura.ae',
                    'phone' => '971567354912',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Al Quoz',
                    'created_dt' => '10/30/2018 19:07',
                ),
                4 =>
                array(
                    'id' => 226,
                    'full_name' => 'PLANT POWER',
                    'email' => 'Plantpower@logx.com',
                    'phone' => '971506983722',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ4',
                    'created_dt' => '11/1/2018 21:02',
                ),
                5 =>
                array(
                    'id' => 232,
                    'full_name' => 'FITNESS FEEDZ',
                    'email' => 'FitnessFeedz@foodiebrands.com',
                    'phone' => '971529101282',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '11/1/2018 21:26',
                ),
                6 =>
                array(
                    'id' => 240,
                    'full_name' => 'REVIVRE LABS',
                    'email' => 'Bruno@revivre-labs.com',
                    'phone' => '971565484397',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '11/1/2018 21:39',
                ),
                7 =>
                array(
                    'id' => 263,
                    'full_name' => 'KETO LIFE',
                    'email' => 'keto@logx.com',
                    'phone' => '971566734640',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'ABU DHABI',
                    'created_dt' => '11/2/2018 20:50',
                ),
                8 =>
                array(
                    'id' => 455,
                    'full_name' => 'ATHLETES KITCHEN',
                    'email' => 'athleteskitchenuae@gmail.com',
                    'phone' => '971506558282',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'al warqa',
                    'created_dt' => '11/3/2018 15:02',
                ),
                9 =>
                array(
                    'id' => 536,
                    'full_name' => 'SMITH ST. PALEO',
                    'email' => 'hello@smithstpaleo.com',
                    'phone' => '971558916106',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ 1',
                    'created_dt' => '11/7/2018 7:50',
                ),
                10 =>
                array(
                    'id' => 791,
                    'full_name' => 'SLICES CATERING SERVICES LLC',
                    'email' => 'paul@slices.ae',
                    'phone' => '971525063027',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ4',
                    'created_dt' => '11/14/2018 19:57',
                ),
                11 =>
                array(
                    'id' => 1331,
                    'full_name' => 'EAT CLEAN LLC',
                    'email' => 'info@eatcleanme.com',
                    'phone' => '971504289908',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '11/29/2018 13:08',
                ),
                12 =>
                array(
                    'id' => 1341,
                    'full_name' => 'Aleix Garcia  3',
                    'email' => 'moazam27@gmail.com',
                    'phone' => '971111111111',
                    'Password_partner' => '',
                    'plain_password' => '',
                    'address' => 'Sama Tower, #2104, Sheikh Zayed Road Sheikh Zayed Road, Sheikh Zayed Road',
                    'created_dt' => '12/2/2018 1:29',
                ),
                13 =>
                array(
                    'id' => 2243,
                    'full_name' => 'TEST PARTNER',
                    'email' => 'sami@thelogx.com',
                    'phone' => '971-147852369',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '2/15/2019 15:28',
                ),
                14 =>
                array(
                    'id' => 2889,
                    'full_name' => 'PROTEIN HOUSE WARQA',
                    'email' => 'Dunia@fithub.ae',
                    'phone' => '971509001234',
                    'Password_partner' => 'Protein',
                    'plain_password' => '',
                    'address' => 'AL WARQA MALL.',
                    'created_dt' => '2/17/2019 18:35',
                ),
                15 =>
                array(
                    'id' => 3484,
                    'full_name' => 'COLOUR MY PLATE',
                    'email' => 'marryjoyperez02@gmail.com',
                    'phone' => '971509351013',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'VOLANTE TOWER',
                    'created_dt' => '2/28/2019 11:59',
                ),
                16 =>
                array(
                    'id' => 6677,
                    'full_name' => 'EAT CONSCIOUS',
                    'email' => 'cc@eatconscious.ae',
                    'phone' => '971552500905',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ',
                    'created_dt' => '6/22/2019 10:25',
                ),
                17 =>
                array(
                    'id' => 7018,
                    'full_name' => 'Moazam',
                    'email' => ' ',
                    'phone' => '923310423657',
                    'Password_partner' => '',
                    'plain_password' => '',
                    'address' => 'Lahore',
                    'created_dt' => '6/24/2019 16:41',
                ),
                18 =>
                array(
                    'id' => 7032,
                    'full_name' => 'Rana Touqeer Attique',
                    'email' => 'touqeerattiq@gmail.com',
                    'phone' => '971123456789',
                    'Password_partner' => '',
                    'plain_password' => '',
                    'address' => '181 Kamran Block Allama Iqbal Town',
                    'created_dt' => '6/25/2019 16:09',
                ),
                19 =>
                array(
                    'id' => 7035,
                    'full_name' => 'test',
                    'email' => ' ',
                    'phone' => '971550087976',
                    'Password_partner' => '',
                    'plain_password' => '',
                    'address' => 'Lahore',
                    'created_dt' => '6/25/2019 18:09',
                ),
                20 =>
                array(
                    'id' => 7550,
                    'full_name' => 'SLICES CATERING',
                    'email' => 'cpuslices@gmail.com',
                    'phone' => '971563659913',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ',
                    'created_dt' => '7/15/2019 10:57',
                ),
                21 =>
                array(
                    'id' => 8315,
                    'full_name' => 'Slices Cash Collection',
                    'email' => 'accounts@thelogx.com',
                    'phone' => '971549986424',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Barsha 1',
                    'created_dt' => '8/20/2019 17:20',
                ),
                22 =>
                array(
                    'id' => 8957,
                    'full_name' => 'KETO BY FOXXY',
                    'email' => 'foxxy@gmail.com',
                    'phone' => '971589996460',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '9/4/2019 9:32',
                ),
                23 =>
                array(
                    'id' => 10294,
                    'full_name' => 'GOURMET GRAND GROCER',
                    'email' => 'gxthomas@grandgourmetgrocer.com',
                    'phone' => '971555440458',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'PALM JUMEIRAH',
                    'created_dt' => '10/7/2019 18:30',
                ),
                24 =>
                array(
                    'id' => 10537,
                    'full_name' => 'ALOFT HOTEL',
                    'email' => 'Midhun.Dharmarajan@marriott.com',
                    'phone' => '971874847482',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '10/14/2019 13:54',
                ),
                25 =>
                array(
                    'id' => 10804,
                    'full_name' => 'NOURISHING DUBAI',
                    'email' => 'jeff@nourishingdubai.com',
                    'phone' => '971505387133',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '10/21/2019 13:11',
                ),
                26 =>
                array(
                    'id' => 11024,
                    'full_name' => 'BEAST MODE NU TRITION',
                    'email' => 'ashlynn@beast-mode-nu trition.com ',
                    'phone' => '971528936660',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Room 304 Hilton double tree Jbr Dubai   Other  Dubai(Jumeirah Beach Residence)',
                    'created_dt' => '10/28/2019 13:48',
                ),
                27 =>
                array(
                    'id' => 12022,
                    'full_name' => 'SNACK STUDIO',
                    'email' => 'snackstudio@gmail.com',
                    'phone' => '971583124404',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Foodie Brands',
                    'created_dt' => '11/18/2019 11:47',
                ),
                28 =>
                array(
                    'id' => 12803,
                    'full_name' => 'ESSENTIALLY',
                    'email' => 'kitchen@essentially.ae',
                    'phone' => '557563207',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Quoz 3',
                    'created_dt' => '',
                ),
                29 =>
                array(
                    'id' => 13287,
                    'full_name' => 'HEALTHY TEDDY',
                    'email' => 'moe@healthyteddy.net',
                    'phone' => '971-566652909',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                30 =>
                array(
                    'id' => 14689,
                    'full_name' => 'FITNESS KITCHEN',
                    'email' => 'thefitnesskitchenme@gmail.com',
                    'phone' => '971544295924',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'AL QOUZ 1',
                    'created_dt' => '',
                ),
                31 =>
                array(
                    'id' => 14695,
                    'full_name' => 'HACKED KITCHEN DMCC',
                    'email' => 'mujahid_islam@hackedkitchen.com',
                    'phone' => '971559933603',
                    'Password_partner' => 'HK@2020',
                    'plain_password' => 'HK@2020',
                    'address' => 'JLT  Cluster C  Shop C5-04  Dubai',
                    'created_dt' => '',
                ),
                32 =>
                array(
                    'id' => 14812,
                    'full_name' => 'KETO HUB DMCC',
                    'email' => 'info@ketohub.ae',
                    'phone' => '971505205542',
                    'Password_partner' => 'Logxlife1234',
                    'plain_password' => '',
                    'address' => 'DMCC 740745  and Address Unit No: 2237  DMCC Business Centre  Level No. 1  Jewellery & Gemplex 3  Dubai',
                    'created_dt' => '',
                ),
                33 =>
                array(
                    'id' => 16089,
                    'full_name' => 'MR BAKER',
                    'email' => 'ayesha.attique.work@gmail.com',
                    'phone' => '9718372829375',
                    'Password_partner' => '12345',
                    'plain_password' => '',
                    'address' => 'Test_partner Address',
                    'created_dt' => '',
                ),
                34 =>
                array(
                    'id' => 17478,
                    'full_name' => 'MELANGE',
                    'email' => 'hi@melangeme.com',
                    'phone' => '971526349676',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Dubai ',
                    'created_dt' => '',
                ),
                35 =>
                array(
                    'id' => 17573,
                    'full_name' => 'Shaheen M',
                    'email' => 'info@wandersons.ae',
                    'phone' => '971554554441',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Villa 9 -9 31 A St - Garhoud - Dubai-, Dubai(Al Garhoud)',
                    'created_dt' => '',
                ),
                36 =>
                array(
                    'id' => 18084,
                    'full_name' => 'ROSELEAF CAFE',
                    'email' => 'meri@roseleafcafe.com',
                    'phone' => '971506588766',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                37 =>
                array(
                    'id' => 19212,
                    'full_name' => 'KETO BY FOXXY - MEAL PLAN ',
                    'email' => 'KetoByFoxxy@logx.com',
                    'phone' => '971506983722',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ4',
                    'created_dt' => '',
                ),
                38 =>
                array(
                    'id' => 19218,
                    'full_name' => 'THE COOKIE BANDITS',
                    'email' => 'b.javier@foodiebrands.com',
                    'phone' => '971506983722',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ4',
                    'created_dt' => '',
                ),
                39 =>
                array(
                    'id' => 19531,
                    'full_name' => 'COLD PRESSED JUICES',
                    'email' => 's.katende@foodiebrands.com',
                    'phone' => '971506983722',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ4',
                    'created_dt' => '',
                ),
                40 =>
                array(
                    'id' => 19928,
                    'full_name' => 'MILK BAR',
                    'email' => 'Milkbakery.ae@gmail.com',
                    'phone' => '971557744441',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                41 =>
                array(
                    'id' => 20470,
                    'full_name' => 'KETOBITES',
                    'email' => 'Amjad@delibitecatering.com',
                    'phone' => '971506560528',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                42 =>
                array(
                    'id' => 20846,
                    'full_name' => 'NIGHTJAR',
                    'email' => 'accounts@nightjar.coffee',
                    'phone' => '971559153706',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Al Quoz 1',
                    'created_dt' => '',
                ),
                43 =>
                array(
                    'id' => 20916,
                    'full_name' => 'SOIL STORE',
                    'email' => 'alseef@soilstore.com',
                    'phone' => '971501119594',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Abu Dhabi',
                    'created_dt' => '',
                ),
                44 =>
                array(
                    'id' => 21263,
                    'full_name' => 'MUSCLEFUEL',
                    'email' => 'admin@musclefueluae.com',
                    'phone' => '971564131115',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Abu dhabi',
                    'created_dt' => '',
                ),
                45 =>
                array(
                    'id' => 21649,
                    'full_name' => 'PROTEIN BAKESHOP',
                    'email' => 'hello@theproteinbakeshop.com',
                    'phone' => '971529455227',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                46 =>
                array(
                    'id' => 21750,
                    'full_name' => 'ITALIAN CAKE & BAKE',
                    'email' => 'melodygeorge@hotmail.com',
                    'phone' => '971 504508798',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'JLT',
                    'created_dt' => '',
                ),
                47 =>
                array(
                    'id' => 22017,
                    'full_name' => 'BUTTERSCOTCH BAKERY',
                    'email' => 'may@butterscotchbakery.com',
                    'phone' => '971506685238',
                    'Password_partner' => 'Logxlife1234',
                    'plain_password' => '',
                    'address' => 'Abu Dhabi',
                    'created_dt' => '',
                ),
                48 =>
                array(
                    'id' => 23074,
                    'full_name' => 'ELEGANT GIFT WRAPPING',
                    'email' => 'katrina@alrais.ae',
                    'phone' => '971505798612',
                    'Password_partner' => 'Logxlife1234',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                49 =>
                array(
                    'id' => 23487,
                    'full_name' => 'WASLA',
                    'email' => 'alreem@waslanow.com',
                    'phone' => '971505611066',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'MIZHAR ',
                    'created_dt' => '',
                ),
                50 =>
                array(
                    'id' => 23541,
                    'full_name' => 'NUTRIBEAST',
                    'email' => 'leon@kitchenkollectiv.com',
                    'phone' => '971505522463',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QUOZ 4',
                    'created_dt' => '',
                ),
                51 =>
                array(
                    'id' => 23756,
                    'full_name' => 'STASH BEAUTY LTD',
                    'email' => 'stashwithlove@outlook.com',
                    'phone' => '971504425269',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                52 =>
                array(
                    'id' => 23844,
                    'full_name' => 'KETO FRESH',
                    'email' => 'ala.jebrini@gmail.com',
                    'phone' => '971529256000',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Barsha',
                    'created_dt' => '',
                ),
                53 =>
                array(
                    'id' => 23927,
                    'full_name' => 'RAWKURE LLC',
                    'email' => 'rawkuremealplans@foodiebrands.com',
                    'phone' => '9715 6017881',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ4',
                    'created_dt' => '',
                ),
                54 =>
                array(
                    'id' => 25020,
                    'full_name' => 'NUTRI ',
                    'email' => 'nutri@thelogx.com',
                    'phone' => '971504066993',
                    'Password_partner' => 'Logxlife1234',
                    'plain_password' => '',
                    'address' => 'Abu Dhabi',
                    'created_dt' => '',
                ),
                55 =>
                array(
                    'id' => 26911,
                    'full_name' => 'THE BEET BOX',
                    'email' => 'people@thebeetbox.me',
                    'phone' => '971553647300',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                56 =>
                array(
                    'id' => 27341,
                    'full_name' => 'WOROOD INTRAFLORA',
                    'email' => 'hetal@worood.com',
                    'phone' => '971561737335',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Mall Of The Emirates',
                    'created_dt' => '',
                ),
                57 =>
                array(
                    'id' => 27563,
                    'full_name' => 'Live Right DMCC (Eat Right)',
                    'email' => 'vh@theliveright.com',
                    'phone' => '971551903770',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'UAE',
                    'created_dt' => '',
                ),
                58 =>
                array(
                    'id' => 27936,
                    'full_name' => 'EAT WELL',
                    'email' => 'a.helmy@dubaieatwell.com',
                    'phone' => '971586851226',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                59 =>
                array(
                    'id' => 28153,
                    'full_name' => 'SAHTEIN',
                    'email' => 'Dokhanchi@sahtein.ae',
                    'phone' => '971547964111',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                60 =>
                array(
                    'id' => 28286,
                    'full_name' => 'ZERO FAT',
                    'email' => 'zerofat@logx.com',
                    'phone' => '971502269880',
                    'Password_partner' => 'r4ldgrpt',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                61 =>
                array(
                    'id' => 30329,
                    'full_name' => 'test_partner_for_new_release',
                    'email' => 'hello@thelogx.com',
                    'phone' => '971098676768',
                    'Password_partner' => '12345',
                    'plain_password' => '',
                    'address' => 'Test_partner Address for new',
                    'created_dt' => '',
                ),
                62 =>
                array(
                    'id' => 32994,
                    'full_name' => 'THE RAW PLACE ',
                    'email' => 'hashir@therawplace.com',
                    'phone' => '971508943408',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'AL QOUZ',
                    'created_dt' => '',
                ),
                63 =>
                array(
                    'id' => 33589,
                    'full_name' => 'THE CYCLE HUB',
                    'email' => 'frane@thecyclehub.com',
                    'phone' => '971545205840',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Unit 6B Dubai Autodrome Retail Plaza - Motor City - Dubai',
                    'created_dt' => '',
                ),
                64 =>
                array(
                    'id' => 33906,
                    'full_name' => 'LOGX Transport LLC',
                    'email' => 'logxdxb@gmail.com',
                    'phone' => '971456456456',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                65 =>
                array(
                    'id' => 34238,
                    'full_name' => 'GROW UAE',
                    'email' => 'Info@growuae.com',
                    'phone' => '971507283823',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                66 =>
                array(
                    'id' => 34768,
                    'full_name' => 'BE-MORE KETO',
                    'email' => 'operations@ketogoodiesdubai.com',
                    'phone' => '971585896443',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                67 =>
                array(
                    'id' => 36502,
                    'full_name' => 'UTRITION',
                    'email' => 'utrition@alahligroup.com',
                    'phone' => '971543071312',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                68 =>
                array(
                    'id' => 37535,
                    'full_name' => 'Do Not Use - OLD Fitkult',
                    'email' => 'jfares@fitkult.me',
                    'phone' => '545448445',
                    'Password_partner' => '78601',
                    'plain_password' => '',
                    'address' => 'ALQOUZ 3',
                    'created_dt' => '',
                ),
                69 =>
                array(
                    'id' => 38833,
                    'full_name' => 'FITBITES',
                    'email' => 'fitbites@thelogx.com',
                    'phone' => '97152226910',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                70 =>
                array(
                    'id' => 40062,
                    'full_name' => 'Test Partner Ayesha Attique',
                    'email' => 'atiqshazzia104@gmail.com',
                    'phone' => '9713228009002',
                    'Password_partner' => '12345',
                    'plain_password' => '',
                    'address' => 'Test street#2 Test Town',
                    'created_dt' => '',
                ),
                71 =>
                array(
                    'id' => 40194,
                    'full_name' => 'HONEST BADGER FOODS',
                    'email' => 'hello@honestbadgerfoods.com',
                    'phone' => '971-502234981',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'AL QOUZ 3',
                    'created_dt' => '',
                ),
                72 =>
                array(
                    'id' => 40624,
                    'full_name' => '77 VEGGIE',
                    'email' => 'manish@77veggie.com',
                    'phone' => '971-559851077',
                    'Password_partner' => 'cancelled',
                    'plain_password' => '',
                    'address' => 'DIP DUBAI',
                    'created_dt' => '',
                ),
                73 =>
                array(
                    'id' => 41120,
                    'full_name' => 'HOME MADE DUBAI',
                    'email' => 'homemadedxb@foodiebrands.com',
                    'phone' => '971585824714',
                    'Password_partner' => 'Homemade2021',
                    'plain_password' => '',
                    'address' => 'ALQOUZ',
                    'created_dt' => '',
                ),
                74 =>
                array(
                    'id' => 41156,
                    'full_name' => 'Wajabat',
                    'email' => 'wajabat@gmail.com',
                    'phone' => '971585232389',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'ABU DHABI',
                    'created_dt' => '',
                ),
                75 =>
                array(
                    'id' => 43004,
                    'full_name' => 'KETO FOR LESS',
                    'email' => 'KFL@THELOGX.COM',
                    'phone' => '971543197214',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ',
                    'created_dt' => '',
                ),
                76 =>
                array(
                    'id' => 43158,
                    'full_name' => 'Cody Barrett',
                    'email' => 'c.zablan@foodiebrands.com',
                    'phone' => '971501522348',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => '22 Street Alquoz 3, Foodie Brands Catering Services, Dubai(OTHER)',
                    'created_dt' => '',
                ),
                77 =>
                array(
                    'id' => 44010,
                    'full_name' => 'COLES',
                    'email' => 'Coles@thelogx.com',
                    'phone' => '971501521234',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'ABU DHABI',
                    'created_dt' => '',
                ),
                78 =>
                array(
                    'id' => 44061,
                    'full_name' => 'Well emirates',
                    'email' => 'wellemirates@thelogx.com',
                    'phone' => '971520012345',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'ABU DHABI',
                    'created_dt' => '',
                ),
                79 =>
                array(
                    'id' => 44313,
                    'full_name' => 'Klean',
                    'email' => 'klean@thelogx.com',
                    'phone' => '971520012345',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL Quoz 4',
                    'created_dt' => '',
                ),
                80 =>
                array(
                    'id' => 45305,
                    'full_name' => 'MEALPLANS.AE',
                    'email' => 'mealplan.ae@thelogx.com',
                    'phone' => '971520012340',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Healthcare city',
                    'created_dt' => '',
                ),
                81 =>
                array(
                    'id' => 46044,
                    'full_name' => 'VITAMIN V ',
                    'email' => 'Vitaminv@thelogx.com',
                    'phone' => '971520012345',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Khawaneej',
                    'created_dt' => '',
                ),
                82 =>
                array(
                    'id' => 46507,
                    'full_name' => 'Testing ABC',
                    'email' => 'shaziaattiq033@gmail.com',
                    'phone' => '971399875391912',
                    'Password_partner' => '12345',
                    'plain_password' => '',
                    'address' => 'Testing Address',
                    'created_dt' => '',
                ),
                83 =>
                array(
                    'id' => 47467,
                    'full_name' => 'SAGE',
                    'email' => 'sage@thelogx.com',
                    'phone' => '971520012345',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Barsha 1',
                    'created_dt' => '',
                ),
                84 =>
                array(
                    'id' => 48007,
                    'full_name' => 'iDiet',
                    'email' => 'iDiet@foodiebrands.com',
                    'phone' => '971547068130',
                    'Password_partner' => 'idiet',
                    'plain_password' => '',
                    'address' => 'Al Quoz',
                    'created_dt' => '',
                ),
                85 =>
                array(
                    'id' => 48146,
                    'full_name' => 'Pop Dubai',
                    'email' => 'popdubai@foodiebrands.com',
                    'phone' => '971520012389',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Quoz',
                    'created_dt' => '',
                ),
                86 =>
                array(
                    'id' => 49419,
                    'full_name' => 'Springbok',
                    'email' => 'Springbok@thelogx.com',
                    'phone' => '971520012345',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Gorilla Kitchen',
                    'created_dt' => '',
                ),
                87 =>
                array(
                    'id' => 49804,
                    'full_name' => 'Pear',
                    'email' => 'pear@thelogx.com',
                    'phone' => '971520012346',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Gorilla Kitchen',
                    'created_dt' => '',
                ),
                88 =>
                array(
                    'id' => 49847,
                    'full_name' => 'Sahara Catering',
                    'email' => 'saharacatering@thelogx.com',
                    'phone' => '971520012346',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Barsha 1',
                    'created_dt' => '',
                ),
                89 =>
                array(
                    'id' => 52074,
                    'full_name' => 'PROTEIN HOUSE AL WASL - Reem',
                    'email' => 'Nourhanybarbar@gmail.com',
                    'phone' => '971-222554681',
                    'Password_partner' => '1234ABCD',
                    'plain_password' => '',
                    'address' => 'ALWASL',
                    'created_dt' => '',
                ),
                90 =>
                array(
                    'id' => 53018,
                    'full_name' => 'EroeGo',
                    'email' => 'EroeGo@thelogx.com',
                    'phone' => '971520019874',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'ras al khor',
                    'created_dt' => '',
                ),
                91 =>
                array(
                    'id' => 53207,
                    'full_name' => 'FITFOOD',
                    'email' => 'fitfood@thelogx.com',
                    'phone' => '971520011233',
                    'Password_partner' => 'gv09m2of',
                    'plain_password' => '',
                    'address' => 'Be more keto',
                    'created_dt' => '',
                ),
                92 =>
                array(
                    'id' => 53524,
                    'full_name' => 'POKE & CO',
                    'email' => 'POKE@THELOGX.COM',
                    'phone' => '971523760564',
                    'Password_partner' => 'ttqnx85t',
                    'plain_password' => '',
                    'address' => 'JLT',
                    'created_dt' => '',
                ),
                93 =>
                array(
                    'id' => 53822,
                    'full_name' => 'PROTEIN HOUSE ALMIZHAR',
                    'email' => 'ph@fithub.ae',
                    'phone' => '971507455933',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Dubai Mizhar',
                    'created_dt' => '',
                ),
                94 =>
                array(
                    'id' => 54329,
                    'full_name' => 'Low Carb City',
                    'email' => 'LowCarbCity@thelogx.com',
                    'phone' => '971585896489',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                95 =>
                array(
                    'id' => 54739,
                    'full_name' => 'Haute Sauce',
                    'email' => 'hautesauce@thelogx.com',
                    'phone' => '971568839474',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                96 =>
                array(
                    'id' => 54740,
                    'full_name' => 'Health Road',
                    'email' => 'healthroad@thelogx.com',
                    'phone' => '971552097442',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                97 =>
                array(
                    'id' => 55164,
                    'full_name' => 'BASILIGO RESTAURANT LLC',
                    'email' => 'basiligo@thelogx.com',
                    'phone' => '971545180219',
                    'Password_partner' => 'Fresh@2022',
                    'plain_password' => 'Fresh@2022',
                    'address' => 'ABU DHABI',
                    'created_dt' => '',
                ),
                98 =>
                array(
                    'id' => 55274,
                    'full_name' => '8020 PREP',
                    'email' => '8020@foodiebrands.com',
                    'phone' => '971-562443199',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                99 =>
                array(
                    'id' => 55457,
                    'full_name' => 'KETO GOODIES',
                    'email' => 'SOCIALMEDIA.KETOGOODIES@GMAIL.COM',
                    'phone' => '971585896443',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'INTERNATIONAL CITY GREECE CLUSTER',
                    'created_dt' => '',
                ),
                100 =>
                array(
                    'id' => 55540,
                    'full_name' => 'LoseWeight',
                    'email' => 'loseweight@thelogx.com',
                    'phone' => '9715451817947',
                    'Password_partner' => 'Fresh@2022',
                    'plain_password' => 'Fresh@2022',
                    'address' => 'ABU DHABI',
                    'created_dt' => '',
                ),
                101 =>
                array(
                    'id' => 55941,
                    'full_name' => 'Healthy Fresh',
                    'email' => 'healthyfresh@thelogx.com',
                    'phone' => '971551234789',
                    'Password_partner' => 'Fresh@2022',
                    'plain_password' => 'Fresh@2022',
                    'address' => 'ABU DHABI',
                    'created_dt' => '',
                ),
                102 =>
                array(
                    'id' => 56266,
                    'full_name' => 'Tasting Bay ',
                    'email' => 'tastingbay@thelogx.com',
                    'phone' => '971507055118',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                103 =>
                array(
                    'id' => 59248,
                    'full_name' => 'Freshly',
                    'email' => 'freshly@thelogx.com',
                    'phone' => '971551234789',
                    'Password_partner' => 'Fresh@2022',
                    'plain_password' => '',
                    'address' => 'ras al khor',
                    'created_dt' => '',
                ),
                104 =>
                array(
                    'id' => 59316,
                    'full_name' => 'BE BALANCE',
                    'email' => 'bebalance@thelogx.com',
                    'phone' => '971529199220',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                105 =>
                array(
                    'id' => 59846,
                    'full_name' => 'BE SWEET',
                    'email' => 'bsweet@thelogx.com',
                    'phone' => '971545180211',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'ABU DHABI',
                    'created_dt' => '',
                ),
                106 =>
                array(
                    'id' => 60684,
                    'full_name' => 'Saba Plant Based',
                    'email' => 'sabaplantbased@thelogx.com',
                    'phone' => '971557243231',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Quoz',
                    'created_dt' => '',
                ),
                107 =>
                array(
                    'id' => 61344,
                    'full_name' => 'Pro Bar Gym',
                    'email' => 'probargym@thelogx.com',
                    'phone' => '971585854493',
                    'Password_partner' => 'i7h68i8t',
                    'plain_password' => '',
                    'address' => 'ras al khor',
                    'created_dt' => '',
                ),
                108 =>
                array(
                    'id' => 61469,
                    'full_name' => 'MunchBox',
                    'email' => 'munchbox@thelogx.com',
                    'phone' => '971588781750',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Jabel Ali',
                    'created_dt' => '',
                ),
                109 =>
                array(
                    'id' => 62566,
                    'full_name' => 'Go Organic',
                    'email' => 'Goorganic@thelogx.com',
                    'phone' => '971563906460',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai Investment Park',
                    'created_dt' => '',
                ),
                110 =>
                array(
                    'id' => 63586,
                    'full_name' => 'Healthy Roots',
                    'email' => 'Healthyroots@thelogx.com',
                    'phone' => '971502016881',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Ajman',
                    'created_dt' => '',
                ),
                111 =>
                array(
                    'id' => 64252,
                    'full_name' => 'The Health Co.',
                    'email' => 'thehealthco@thelogx.com',
                    'phone' => '971563283593',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'al quoz',
                    'created_dt' => '',
                ),
                112 =>
                array(
                    'id' => 65771,
                    'full_name' => 'National Bonds',
                    'email' => 'nationalbond@thelogx.com',
                    'phone' => '9715781031544',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'AL QOUZ4',
                    'created_dt' => '',
                ),
                113 =>
                array(
                    'id' => 66279,
                    'full_name' => 'The Luxe Basket',
                    'email' => 'theluxebasket@thelogx.com',
                    'phone' => '971503936812',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Jabel Ali',
                    'created_dt' => '',
                ),
                114 =>
                array(
                    'id' => 66345,
                    'full_name' => 'Love Food Me',
                    'email' => 'Admin1@lovefoodme.com',
                    'phone' => '971-564200127',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Quoz',
                    'created_dt' => '',
                ),
                115 =>
                array(
                    'id' => 67901,
                    'full_name' => 'Sharethelove',
                    'email' => 'Sharethelove@thelogx.com',
                    'phone' => '971-504464477',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Silicon Oasis',
                    'created_dt' => '',
                ),
                116 =>
                array(
                    'id' => 68783,
                    'full_name' => 'Coba Cafe',
                    'email' => 'cobacafe@thelogx.com',
                    'phone' => '971556683998',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Quoz',
                    'created_dt' => '',
                ),
                117 =>
                array(
                    'id' => 70006,
                    'full_name' => 'Warner Bros',
                    'email' => 'warnerbros@thelogx.com',
                    'phone' => '971-553957821',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                118 =>
                array(
                    'id' => 71102,
                    'full_name' => 'Nutrition Kitchen',
                    'email' => 'NutritionKitchen@thelogx.com',
                    'phone' => '971-5544805',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'Yas Island',
                    'created_dt' => '',
                ),
                119 =>
                array(
                    'id' => 74246,
                    'full_name' => 'Do Not Use - OLD KARMA8',
                    'email' => 'OLDKARMA8@thelogx.com',
                    'phone' => '9715055000000',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Quoz 3',
                    'created_dt' => '',
                ),
                120 =>
                array(
                    'id' => 74922,
                    'full_name' => 'Little Bento',
                    'email' => 'littlebento@thelogx.com',
                    'phone' => '9715055000014',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Quoz 3',
                    'created_dt' => '',
                ),
                121 =>
                array(
                    'id' => 75623,
                    'full_name' => 'Lunch It',
                    'email' => 'Lunchit@thelogx.com',
                    'phone' => '971505500014',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Abu Dhabi',
                    'created_dt' => '',
                ),
                122 =>
                array(
                    'id' => 75877,
                    'full_name' => 'Karma8',
                    'email' => 'operations@karma8.ae',
                    'phone' => '971-585126852',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                123 =>
                array(
                    'id' => 76907,
                    'full_name' => 'BEAN & BEYOND FARM L.L.C',
                    'email' => 'Beanandbeyond@thelogx.com',
                    'phone' => '97150124871',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DIP',
                    'created_dt' => '',
                ),
                124 =>
                array(
                    'id' => 76954,
                    'full_name' => 'Prime Gourmet',
                    'email' => 'primegourmet@thelogx.com',
                    'phone' => '97150164145674',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Quoz 3',
                    'created_dt' => '',
                ),
                125 =>
                array(
                    'id' => 78250,
                    'full_name' => 'BYou',
                    'email' => 'BYou@thelogx.com',
                    'phone' => '97150164145684',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                126 =>
                array(
                    'id' => 79182,
                    'full_name' => 'Nutri Bliss',
                    'email' => 'NutriBliss@thelogx.com',
                    'phone' => '971527547689',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Keto Life Kitchen',
                    'created_dt' => '',
                ),
                127 =>
                array(
                    'id' => 80144,
                    'full_name' => 'MomIT',
                    'email' => 'MomIT@thelogx.com',
                    'phone' => '971504734517',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                128 =>
                array(
                    'id' => 80497,
                    'full_name' => 'Dr. Food - OLD',
                    'email' => 'DrFood@thelogx.com',
                    'phone' => '971501212852',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                129 =>
                array(
                    'id' => 82043,
                    'full_name' => 'Foodie IDIET',
                    'email' => 'foodieIDIET@thelogx.com',
                    'phone' => '971-585790147',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                130 =>
                array(
                    'id' => 82672,
                    'full_name' => 'Nom Nom Pet Treats',
                    'email' => 'Nomnom@thelogx.com',
                    'phone' => '556611367',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                131 =>
                array(
                    'id' => 83058,
                    'full_name' => 'Breads On Us',
                    'email' => 'breadsonus@thelogx.com',
                    'phone' => '971507891160',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                132 =>
                array(
                    'id' => 83221,
                    'full_name' => 'Right Farm',
                    'email' => 'rightfarm@thelogx.com',
                    'phone' => '9711245796307',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                133 =>
                array(
                    'id' => 86949,
                    'full_name' => 'Thawaaq Foodstuff',
                    'email' => 'Thawaaq@thelogx.com',
                    'phone' => '9715123647852',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                134 =>
                array(
                    'id' => 88078,
                    'full_name' => 'Nutri Eats',
                    'email' => 'NutriEats@thelogx.com',
                    'phone' => '971565484397',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                135 =>
                array(
                    'id' => 88580,
                    'full_name' => 'DUB Meals',
                    'email' => 'dubmeals@thelogx.com',
                    'phone' => '971147856923',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Foodie',
                    'created_dt' => '',
                ),
                136 =>
                array(
                    'id' => 90053,
                    'full_name' => 'JT International Support Services',
                    'email' => 'jti@thelogx.com',
                    'phone' => '971551191765',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Foodie',
                    'created_dt' => '',
                ),
                137 =>
                array(
                    'id' => 90609,
                    'full_name' => 'Sealed LLC',
                    'email' => 'SealedLLC@thelogx.com',
                    'phone' => '971503781011',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                138 =>
                array(
                    'id' => 92565,
                    'full_name' => 'Atelier Foodstuff Trading LLC',
                    'email' => 'Atelier@thelogx.com',
                    'phone' => '971147852369',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                139 =>
                array(
                    'id' => 93653,
                    'full_name' => 'VENDY FOR VENDING MACHINES TRADING',
                    'email' => 'vendy@thelogx.com',
                    'phone' => '971552109940',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                140 =>
                array(
                    'id' => 93828,
                    'full_name' => ' BEBOXA TRADING L.L.C',
                    'email' => 'beboxa@thelogx.com',
                    'phone' => '971585021700971',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                141 =>
                array(
                    'id' => 93870,
                    'full_name' => 'Traybae LLC',
                    'email' => 'traybae@thelogx.com',
                    'phone' => '971553017724',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                142 =>
                array(
                    'id' => 94171,
                    'full_name' => 'Fitkult',
                    'email' => 'Fitkult@logx.com',
                    'phone' => '971-545448445',
                    'Password_partner' => 'i7z5n68p',
                    'plain_password' => '',
                    'address' => 'ALQOUZ 3',
                    'created_dt' => '',
                ),
                143 =>
                array(
                    'id' => 94477,
                    'full_name' => 'Lei & Co ',
                    'email' => 'lei&co@thelogx.com',
                    'phone' => '971544444446',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                144 =>
                array(
                    'id' => 94480,
                    'full_name' => 'Moneypit',
                    'email' => 'moneypit@thelogx.com',
                    'phone' => '971533333333',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                145 =>
                array(
                    'id' => 94936,
                    'full_name' => 'PROTEIN HOUSE AL WASL - Marwa',
                    'email' => 'marwa@logx.com',
                    'phone' => '971-222554444',
                    'Password_partner' => '3467896',
                    'plain_password' => '3467896',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                146 =>
                array(
                    'id' => 95442,
                    'full_name' => 'Boxica',
                    'email' => 'boxica@thelogx.com',
                    'phone' => '9715555505050',
                    'Password_partner' => '1234abcd',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                147 =>
                array(
                    'id' => 95520,
                    'full_name' => 'Practical',
                    'email' => 'Practical@thelogx.com',
                    'phone' => '97150145714',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                148 =>
                array(
                    'id' => 95947,
                    'full_name' => 'Pet Souq',
                    'email' => 'petsouq@thelogx.com',
                    'phone' => '971543898967',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                149 =>
                array(
                    'id' => 96972,
                    'full_name' => 'Boujee for imitation jewellery smithing',
                    'email' => 'boujee@thelogx.com',
                    'phone' => '971 56 644 8989',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Logx wear house B4 near gold and diamond park',
                    'created_dt' => '',
                ),
                150 =>
                array(
                    'id' => 96999,
                    'full_name' => 'POKE SOUQ',
                    'email' => 'admin@pokesouq.com',
                    'phone' => '971501522348',
                    'Password_partner' => 'Poke1234@',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                151 =>
                array(
                    'id' => 97388,
                    'full_name' => 'HOOF',
                    'email' => 'hoof@thelogx.com',
                    'phone' => '971 56 784 9498',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                152 =>
                array(
                    'id' => 98075,
                    'full_name' => 'Al Mahmasani',
                    'email' => 'almahmasani@thelogx.com',
                    'phone' => '971509532778',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                153 =>
                array(
                    'id' => 98387,
                    'full_name' => 'BE MORE HEALTHY',
                    'email' => 'Bemorehealthy@thelogx.com',
                    'phone' => '971501047457',
                    'Password_partner' => 'rmmzrfl5',
                    'plain_password' => '',
                    'address' => 'Marsha Village marina',
                    'created_dt' => '',
                ),
                154 =>
                array(
                    'id' => 99025,
                    'full_name' => 'Ree7an Kitchen',
                    'email' => 'Ree7an@thelogx.com',
                    'phone' => '971508738524',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Business bay  executive bay tower Alamal street Shop number 16 Backside of the building',
                    'created_dt' => '',
                ),
                155 =>
                array(
                    'id' => 102522,
                    'full_name' => 'House Of Tagine',
                    'email' => 'houseoftagine@thelogx.com',
                    'phone' => '971-556993974',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                156 =>
                array(
                    'id' => 103171,
                    'full_name' => 'Dr. Food.ae',
                    'email' => 'DrFood.ae@thelogx.com',
                    'phone' => '971501212966',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Eat well Kitchen',
                    'created_dt' => '',
                ),
                157 =>
                array(
                    'id' => 103463,
                    'full_name' => 'Ali Al Hashmi Trading LLC',
                    'email' => 'alialhashmitrading@thelogx.com',
                    'phone' => '971544417998',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                158 =>
                array(
                    'id' => 103610,
                    'full_name' => 'PRODIGY',
                    'email' => 'prodigy@thelogx.com',
                    'phone' => '971555157662',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'DUBAI',
                    'created_dt' => '',
                ),
                159 =>
                array(
                    'id' => 104986,
                    'full_name' => 'Fit N Fast Restaurant',
                    'email' => 'FitNFast@thelogx.com',
                    'phone' => '971-526049366',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Al Mizhar 1 - Dubai',
                    'created_dt' => '',
                ),
                160 =>
                array(
                    'id' => 105384,
                    'full_name' => 'TYF',
                    'email' => 'TYF@thelogx.com',
                    'phone' => '971-526188628',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Pura Kitchen',
                    'created_dt' => '',
                ),
                161 =>
                array(
                    'id' => 105772,
                    'full_name' => 'IDIET Pastry',
                    'email' => 'idietpastry@thelogx.com',
                    'phone' => '971-588147117',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Foodie',
                    'created_dt' => '',
                ),
                162 =>
                array(
                    'id' => 107236,
                    'full_name' => 'Pinoy Delicacies',
                    'email' => 'pinoydelicacies@thelogx.com',
                    'phone' => '971-552012983',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Abu Dhabi',
                    'created_dt' => '',
                ),
                163 =>
                array(
                    'id' => 107930,
                    'full_name' => 'Healthy Corner ',
                    'email' => 'HealthyCorner@thelogx.com',
                    'phone' => '971-509889116',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                164 =>
                array(
                    'id' => 108433,
                    'full_name' => 'Yummy Bento',
                    'email' => 'YummyBento@thelogx.com',
                    'phone' => '971-509199278',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                165 =>
                array(
                    'id' => 108586,
                    'full_name' => 'Life Mart',
                    'email' => 'LIfeMart@thelogx.com',
                    'phone' => '79883878775',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                166 =>
                array(
                    'id' => 108941,
                    'full_name' => 'TrainX',
                    'email' => 'Trainx@thelogx.com',
                    'phone' => '971543125516',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                167 =>
                array(
                    'id' => 109862,
                    'full_name' => 'FitBar',
                    'email' => 'FitBar@thelogx.com',
                    'phone' => '971542798259',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                168 =>
                array(
                    'id' => 110913,
                    'full_name' => 'Colnago Cafe',
                    'email' => 'ColnagoCafe@thelogx.com',
                    'phone' => '971568155452',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                169 =>
                array(
                    'id' => 111869,
                    'full_name' => 'Quality Food',
                    'email' => 'qualityfood@thelogx.com',
                    'phone' => '971524353400',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                170 =>
                array(
                    'id' => 111895,
                    'full_name' => 'The White Boutique',
                    'email' => 'TheWhiteBoutique@thelogx.com',
                    'phone' => '971506444155',
                    'Password_partner' => 'ge0hymmi',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                171 =>
                array(
                    'id' => 111969,
                    'full_name' => 'Cloc',
                    'email' => 'Cloc@thelogx.com',
                    'phone' => '971585549342',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                172 =>
                array(
                    'id' => 113711,
                    'full_name' => 'Grams',
                    'email' => 'grams@thelogx.com',
                    'phone' => '971501089895',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Abu Dhabi',
                    'created_dt' => '',
                ),
                173 =>
                array(
                    'id' => 113930,
                    'full_name' => 'Sweet Greens',
                    'email' => 'sweetgreens@thelogx.com',
                    'phone' => '971-586503491',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                174 =>
                array(
                    'id' => 114949,
                    'full_name' => 'Healthy Dose',
                    'email' => 'healthydose@thelogx.com',
                    'phone' => '971-564065654',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'Dubai',
                    'created_dt' => '',
                ),
                175 =>
                array(
                    'id' => 115638,
                    'full_name' => 'Energy Meal Plan',
                    'email' => 'emp@thelogx.com',
                    'phone' => '971-585807846',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
                176 =>
                array(
                    'id' => 116254,
                    'full_name' => 'Mechanics ',
                    'email' => 'Mechanics@thelogx.com',
                    'phone' => '971566154762',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => '...',
                    'created_dt' => '',
                ),
                177 =>
                array(
                    'id' => 116255,
                    'full_name' => 'Prep Meals',
                    'email' => 'prepmeals@thelogx.com',
                    'phone' => '971 54 309 9677',
                    'Password_partner' => 'Logx4321',
                    'plain_password' => '',
                    'address' => 'dubai',
                    'created_dt' => '',
                ),
            )
        );
    }
}
