<?php

namespace Modules\FinanceService\Entities;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Request;
use App\Http\Helper\Helper;
use Modules\BusinessService\Entities\Business;

class BusinessWallet extends Model
{
    use HasFactory;
    use HasUuids;
    use SoftDeletes;

    protected $fillable = [
        'balance',
        'business_id',

    ];

    public function business()
    {
        return $this->belongsTo(Business::class);
    }
    public function cards()
    {
        return $this->hasMany(BusinessCard::class);
    }

    protected static function newFactory()
    {
        return \Modules\FinanceService\Database\factories\BusinessWalletFactory::new();
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            $helper = new Helper();
            $user_id = auth()->id();
            $module_name = "FinanceService";
            $action = "Created";
            $subject = "New Record Created";
            $url = Request::fullUrl();
            $description = "A New Record has been created";
            $ip_address = Request::ip();
            $user_agent = Request::header('user-agent');
            $old_values = null;
            $new_values = json_encode(json_encode($model->getAttributes()));
            $record_id = $model->id;
            $record_type = get_class($model);
            $method = Request::method();

            $helper->logActivity(
                userId: $user_id,
                moduleName: $module_name,
                action: $action,
                subject: $subject,
                url: $url,
                description: $description,
                ipAddress: $ip_address,
                userAgent: $user_agent,
                oldValues: $old_values,
                newValues: $new_values,
                recordId: $record_id,
                recordType: $record_type,
                method: $method
            );
        });

        static::updating(function ($model) {
            $changes = $model->getDirty();

            if ($changes) {
                $helper = new Helper();
                $user_id = auth()->id();
                $module_name = "FinanceService";
                $action = "Updated";
                $subject = "Record Updated";
                $url = Request::fullUrl();
                $description = "Record has been updated";
                $ip_address = Request::ip();
                $user_agent = Request::header('user-agent');
                $old_values = json_encode(json_encode($model->getOriginal()));
                $new_values = json_encode($model->getAttributes());
                $record_id = $model->id;
                $record_type = get_class($model);
                $method = Request::method();

                $helper->logActivity(
                    userId: $user_id,
                    moduleName: $module_name,
                    action: $action,
                    subject: $subject,
                    url: $url,
                    description: $description,
                    ipAddress: $ip_address,
                    userAgent: $user_agent,
                    oldValues: $old_values,
                    newValues: $new_values,
                    recordId: $record_id,
                    recordType: $record_type,
                    method: $method
                );

                // Check if 'balance' attribute is being updated
                if ($model->isDirty('balance')) {
                    $oldBalance = $model->getOriginal('balance');
                    $newBalance = $model->getAttribute('balance');

                    $amount = $newBalance - $oldBalance;
                    $attributes = $model->getAttributes();
                    $wallet_id = $attributes['wallet_id'];
                    



                    // Compare old balance with new balance
                    if ($newBalance > $oldBalance) {
                        $helper->businessWalletTransactions($amount, 'CREDIT', $wallet_id, $payment_method_id = null, $invoice_item_id  = null, $card_id = null);
                    } else {
                        $helper->businessWalletTransactions($amount, 'DEBIT', $wallet_id, $invoice_item_id  = null);
                    }
                }

                if ($model->isDirty('balance')) {
                    $attributes = $model->getAttributes();
                    $helper = new Helper();
                    $action_by = auth()->id();
                    $bag_id = $attributes['id'];
                    $delivery_id = $attributes['id'];
                    $status = $attributes['status'];
                    $vehicle_id = null;
                    $description = "status updated";

                    // Access the related vehicle using the vehicle (through) relationship
                    $vehicle_id = Delivery::find($delivery_id)->deliveryBatch->vehicle->id;

                    $helper->walletdeduction($delivery_id, $status, $action_by, $vehicle_id, $description);

                    // TODO ADD BAGID BY USING RELATIONSHIP OF DELIVERY WITH BAG

                    // $helper->bagTimeline($bag_id, $delivery_id, $status, $action_by, $vehicle_id, $description);
                }
            }
        });

        static::deleting(function ($model) {
            $helper = new Helper();
            $user_id = auth()->id();
            $module_name = "FinanceService";
            $action = "Deleted";
            $subject = "Record Deleted";
            $url = Request::fullUrl();
            $description = "Record has been Deleted";
            $ip_address = Request::ip();
            $user_agent = Request::header('user-agent');
            $old_values = json_encode($model->getOriginal());
            $new_values = null;
            $record_id = $model->id;
            $record_type = get_class($model);
            $method = Request::method();
            $helper->logActivity(
                userId: $user_id,
                moduleName: $module_name,
                action: $action,
                subject: $subject,
                url: $url,
                description: $description,
                ipAddress: $ip_address,
                userAgent: $user_agent,
                oldValues: $old_values,
                newValues: $new_values,
                recordId: $record_id,
                recordType: $record_type,
                method: $method
            );
        });
    }
}
