<?php

namespace Modules\FleetService\Entities;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Request;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Http\Helper\Helper;
use Modules\HRManagement\Entities\Employees;

class VehicleMaintenance extends Model
{
    use HasFactory;
    use HasUuids;
    use SoftDeletes;
    protected $fillable = [
    'vehicle_id',
    'employee_id',
    'maintenance_date',
    'meter_reading',
    'maintenance_category_id',
    'quantity',
    'maintenance_detail',
    'cost',
    'payment_status',
    'paid_date',
    'notes',
    'garage',];

    protected static function newFactory()
    {
        return \Modules\FleetService\Database\factories\VehicleMaintenanceFactory::new();
    }

    public function vehicle(){
        return $this->belongsTo(Vehicle::class);
    }
    public function employee(){
        return $this->belongsTo(Employees::class);
    }
    public function maintenanceCategory(){
        return $this->belongsTo(MaintenanceCategory::class);
    }




    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            $helper = new Helper();
            $user_id = auth()->id();
            $module_name = "FleetService";
            $action = "Created";
            $subject = "New Record Created";
            $url = Request::fullUrl();
            $description = "A New Record has been created";
            $ip_address = Request::ip();
            $user_agent = Request::header('user-agent');
            $old_values = null;
            $new_values = json_encode(json_encode($model->getAttributes()));
            $record_id = $model->id;
            $record_type = get_class($model);
            $method = Request::method();

            $helper->logActivity(userId:$user_id, moduleName: $module_name, action: $action, subject: $subject,
                url: $url, description: $description, ipAddress: $ip_address, userAgent: $user_agent,
                oldValues: $old_values, newValues: $new_values, recordId: $record_id, recordType: $record_type,
                method: $method);
        });

        static::updating(function ($model) {
            $changes = $model->getDirty();

            if ($changes) {
                $helper = new Helper();
                $user_id = auth()->id();
                $module_name = "FleetService";
                $action = "Updated";
                $subject = "Record Updated";
                $url = Request::fullUrl();
                $description = "Record has been updated";
                $ip_address = Request::ip();
                $user_agent = Request::header('user-agent');
                $old_values = json_encode( json_encode($model->getOriginal()));
                $new_values = json_encode($model->getAttributes());
                $record_id = $model->id;
                $record_type = get_class($model);
                $method = Request::method();

                $helper->logActivity(userId:$user_id, moduleName: $module_name, action: $action, subject: $subject,
                    url: $url, description: $description, ipAddress: $ip_address, userAgent: $user_agent,
                    oldValues: $old_values, newValues: $new_values, recordId: $record_id, recordType: $record_type,
                    method: $method);
            }
        });

        static::deleting(function ($model) {
            $helper = new Helper();
            $user_id = auth()->id();
            $module_name = "FleetService";
            $action = "Deleted";
            $subject = "Record Deleted";
            $url = Request::fullUrl();
            $description = "Record has been Deleted";
            $ip_address = Request::ip();
            $user_agent = Request::header('user-agent');
            $old_values =  json_encode($model->getOriginal());
            $new_values = null;
            $record_id = $model->id;
            $record_type = get_class($model);
            $method = Request::method();
            $helper->logActivity(userId:$user_id, moduleName: $module_name, action: $action, subject: $subject,
                url: $url, description: $description, ipAddress: $ip_address, userAgent: $user_agent,
                oldValues: $old_values, newValues: $new_values, recordId: $record_id, recordType: $record_type,
                method: $method);

        });

//        static::retrieved(function ($model) {
//            $helper = new Helper();
//            $user_id = auth()->id();
//            $module_name = "HRM";
//            $action = "Retrieved";
//            $subject = "Record Retrieved";
//            $url = Request::fullUrl();
//            $description = "Record has been retrieved";
//            $ip_address = Request::ip();
//            $user_agent = Request::header('user-agent');
//            $old_values =  json_encode($model->getOriginal());
//            $new_values = json_encode($model->getAttributes());
//            $record_id = $model->id;
//            $record_type = get_class($model);
//            $method = Request::method();
//
//            $helper->logActivity(userId:$user_id, moduleName: $module_name, action: $action, subject: $subject,
//                url: $url, description: $description, ipAddress: $ip_address, userAgent: $user_agent,
//                oldValues: $old_values, newValues: $new_values, recordId: $record_id, recordType: $record_type,
//                method: $method);
//        });
    }
}
